# Generated by Django 5.2.8 on 2025-11-19 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Store Name')),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('zip_code', models.CharField(blank=True, default='', max_length=15, verbose_name='Zip Code')),
                ('phone', models.CharField(blank=True, default='', max_length=25, verbose_name='Phone')),
                ('email_address', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email Address')),
                ('description', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('product_description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('store_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.storeprofile')),
            ],
            options={
                'unique_together': {('store_profile', 'product_name')},
            },
        ),
    ]
